package com.example.healthmateai.ai.diet

import com.example.healthmateai.BuildConfig
import com.example.healthmateai.network.openrouter.OpenRouterApiClient
import com.example.healthmateai.network.openrouter.OpenRouterMessage
import com.example.healthmateai.network.openrouter.OpenRouterRequest
import com.example.healthmateai.network.openrouter.firstMessageContent
import com.example.healthmateai.network.openrouter.openRouterAuthHeader
import com.google.gson.Gson
import com.google.gson.JsonSyntaxException
import java.net.SocketTimeoutException
import java.net.UnknownHostException

class DietPlannerRepository(
    private val gson: Gson = Gson()
) {

    suspend fun generateDietPlan(payload: DietPlanPayload): DietPlan {
        val request = OpenRouterRequest(
            model = BuildConfig.OPENROUTER_MODEL,
            messages = listOf(
                OpenRouterMessage(
                    role = "system",
                    content = "You are HealthMate AI nutrition assistant. Give safe general wellness guidance only. Keep concise. Return strict JSON only with keys: summary, mealSuggestions, hydrationTips, foodsToAvoid, healthyHabits, calorieAwareAdvice. Each key except summary should be an array of short strings."
                ),
                OpenRouterMessage(
                    role = "user",
                    content = buildPrompt(payload)
                )
            ),
            temperature = 0.5,
            maxTokens = 700
        )

        val response = OpenRouterApiClient.service.createChatCompletion(
            authorization = openRouterAuthHeader(),
            request = request
        )

        val content = response.firstMessageContent()
        if (content.isBlank()) {
            throw IllegalStateException("AI returned an empty diet response")
        }

        return parseDietPlan(content)
    }

    private fun buildPrompt(payload: DietPlanPayload): String {
        return """
            Build a personalized diet plan for this profile:
            - diabetes risk: ${"%.0f".format(payload.diabetesRisk * 100)}%
            - heart disease risk: ${"%.0f".format(payload.heartRisk * 100)}%
            - age: ${payload.age ?: "unknown"}
            - BMI: ${payload.bmi?.let { "%.1f".format(it) } ?: "unknown"}
            - weight (kg): ${payload.weight?.let { "%.1f".format(it) } ?: "unknown"}
            - lifestyle inputs: ${payload.lifestyle}

            Requirements:
            1) Include realistic meal ideas for breakfast/lunch/dinner/snacks.
            2) Include hydration targets.
            3) Include foods to avoid for diabetes and heart health.
            4) Include healthy habits and calorie-aware suggestions.
            5) Keep language human and practical.
        """.trimIndent()
    }

    private fun parseDietPlan(raw: String): DietPlan {
        val cleaned = raw.removePrefix("```json").removePrefix("```").removeSuffix("```").trim()
        return try {
            val parsed = gson.fromJson(cleaned, DietPlanJson::class.java)
            DietPlan(
                summary = parsed.summary ?: "Personalized nutrition guidance generated by HealthMate AI.",
                mealSuggestions = parsed.mealSuggestions.orEmpty(),
                hydrationTips = parsed.hydrationTips.orEmpty(),
                foodsToAvoid = parsed.foodsToAvoid.orEmpty(),
                healthyHabits = parsed.healthyHabits.orEmpty(),
                calorieAwareAdvice = parsed.calorieAwareAdvice.orEmpty()
            )
        } catch (_: JsonSyntaxException) {
            DietPlan(
                summary = cleaned,
                mealSuggestions = emptyList(),
                hydrationTips = emptyList(),
                foodsToAvoid = emptyList(),
                healthyHabits = emptyList(),
                calorieAwareAdvice = emptyList()
            )
        }
    }

    fun toReadableError(error: Throwable): String {
        return when (error) {
            is UnknownHostException -> "No internet connection. Connect and try again."
            is SocketTimeoutException -> "Request timed out. Please retry."
            else -> error.message ?: "Could not generate diet plan"
        }
    }
}
